import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ClerkProvider, SignUp } from "@clerk/nextjs";
import { SignedIn, SignedOut } from "@clerk/nextjs/app-beta";
import Navbar from "@/components/Navbar";
const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>
            <Navbar></Navbar>
            {children}
          </SignedIn>
          <SignedOut>
            <SignUp></SignUp>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
